config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/index'
  root 'games#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :games do
    member do
      get :ownerships
    end
  end
  resources :users do
    member do
      get :ownerships
    end
  end

  resources :users, only: [:show, :index]

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :ownerships
	has_many :users, through: :ownerships
end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
	belongs_to :user
	belongs_to :game
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :ownerships
	has_many :games, through: :ownerships

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to '/'
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :rate)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:index]
	before_action :admin_user, only: []
	before_action :correct_user, only: []

  def show
    @user = User.find(params[:id])
  end

  def index
  	@users = User.all
  end

  private
  	def admin_user
  		redirect_to(root_url) unless (current_user && current_user.admin?)
  	end

  	def correct_user
  		@user = User.find(params[:id])
  		redirect_to(root_url) unless @user == current_user
  	end

  	def logged_in_user
  		redirect_to(new_user_session_path) unless current_user
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.text_field :rate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.haml
%h1= "Editing game"

= render 'form'

= link_to 'Show', @game
= link_to 'Back', games_path

app/views/games/index.html.haml
.rectangle
  .rectangle-header
    %h1= "List of all games"
  .rectangle-body
    %table.table.table-condensed
      %tbody
        - @games.each do |game|
          %tr
            %td= game.title
            %td= game.rate
            %td= link_to 'Show', game
            - if (current_user)
              %td= link_to 'Add', '#'
            - if (current_user && current_user.admin?)
              %td= link_to 'Edit', edit_game_path(game)
              %td= link_to 'Destroy', game, method: :delete, data: { confrim: 'Are you sure?' }

    - if (current_user && current_user.admin?)
      =link_to 'New Game', new_game_path

app/views/games/new.html.haml
%h1= "New game"

= render 'form'

= link_to 'Back', games_path

app/views/games/show.html.haml
.rectangle
  .rectangle-header
    %h1= "Games details"
  .rectangle-body
    %p#notice= notice
    %p
      %strong= "Title:"
      = @game.title
    %p
      %strong= "Rate:"
      = @game.rate

    %p
      %strong= "Users owning:"

      %table.table.table-condensed
        %tbody
          - @game.users.each do |user|
            %tr
              %td= user.email
              %td= link_to 'Show user', user_path(user)

    - if (current_user && current_user.admin?)
      %p= link_to 'Edit', edit_game_path(@game)
      %p= link_to 'Add', '#'
      

    %p= link_to 'Back', games_path

app/views/layouts/_footer.html.haml
%footer.footer
	%ul.list-inline
		%li
			= image_tag 'fb.png'
		%li
			= image_tag 'twitter.png'
		%li
			= image_tag 'google.png'

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid.navbar
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      %ul.nav.navbar-nav
        %li
          %h3= link_to "Home", '/'
        %li
          %h3= link_to "Games", games_path
        %li
          %h3= link_to "Gamers", users_index_path
        -if user_signed_in?
          %li
            %h3= link_to "Profile", current_user
          %li 
            %h3= link_to('Logout', destroy_user_session_path, :method => :delete)
        -else
          %li
            %h3= link_to('Login', new_user_session_path)

.jumbotron.text-center
  %h1 Choose your favourite games!
  %h2 Be the one with the biggest games collection
  %span.glyphicon.glyphicon-chevron-down

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "http://fonts.googleapis.com/css?family=Lobster", :rel => "stylesheet", :type => "text/css"}
    %title= "Gamerapp"

  %body
    = render 'layouts/header'
    %p.notice= notice
    %p.alert= alert
    .container.text-center
      .row
        .col-md-3
        .col-md-6
          = yield
        .col-md-3

    = render 'layouts/footer'
      

app/views/users/index.html.haml
.rectangle
  .rectangle-header
    %h1= "List of all users"
  .rectangle-body
    %table.table.table-condensed
      %tbody
        - @users.each do |user|
          %tr
            %td= user.email
            %td= link_to 'Show', user

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/users/show.html.haml
.rectangle
  .rectangle-header
    %h1= "#{ @user.email }'s games"
  .rectangle-body
    %table.table.table-condensed
      %tbody
        - @user.games.each do |game|
          %tr
            %td= game.title
            %td= game.rate
            %td= link_to "Show", game_path(game)